### ISSUE TITLE
Place order method must be updated

### ISSUE THREAD

**Issue by rahulmr** [algobulls/pyalgostrategypool#2]
The examples still using old method.
Please update the same. Instead of below code   
```python
self.main_order[instrument] = \
                self.broker.BuyOrderBracket(instrument=instrument,
                                            order_code=BrokerOrderCodeConstants.INTRADAY,
                                            order_variety=BrokerOrderVarietyConstants.LIMIT,
                                            quantity=qty,
                                            price=ltp,
                                            stoploss_trigger=ltp - (ltp * self.stoploss),
                                            target_trigger=ltp + (ltp * self.target),
                                            trailing_stoploss_trigger=ltp * self.trailing_stoploss)
```
Complete code should be something like below:  
```python
    def strategy_enter_position(self, candle, instrument, sideband_info):
        if sideband_info['action'] == BrokerOrderTransactionTypeConstants.BUY:
            qty = self.number_of_lots * instrument.lot_size
            ltp = self.broker.get_ltp(instrument)
            self.main_order[instrument] = \
                self.broker.place_order(instrument=instrument,
                                        order_transaction_type=BrokerOrderTransactionTypeConstants.BUY,
                                        order_type=BrokerOrderTypeConstants.BRACKET,
                                        order_code=BrokerOrderCodeConstants.INTRADAY,
                                        order_variety=BrokerOrderVarietyConstants.LIMIT,
                                        quantity=qty,
                                        price=ltp,
                                        stoploss_trigger=ltp -
                                        (ltp * self.stoploss),
                                        target_trigger=ltp +
                                        (ltp * self.target),
                                        trailing_stoploss_trigger=ltp * self.trailing_stoploss)

        elif sideband_info['action'] == BrokerOrderTransactionTypeConstants.SELL:
            qty = self.number_of_lots * instrument.lot_size
            ltp = self.broker.get_ltp(instrument)
            self.main_order[instrument] = \
                self.broker.place_order(instrument=instrument,
                                        order_transaction_type=BrokerOrderTransactionTypeConstants.SELL,
                                        order_type=BrokerOrderTypeConstants.BRACKET,
                                        order_code=BrokerOrderCodeConstants.INTRADAY,
                                        order_variety=BrokerOrderVarietyConstants.LIMIT,
                                        quantity=qty,
                                        price=ltp,
                                        stoploss_trigger=ltp +
                                        (ltp * self.stoploss),
                                        target_trigger=ltp -
                                        (ltp * self.target),
                                        trailing_stoploss_trigger=ltp * self.trailing_stoploss)
        else:
            raise SystemExit(
                f'Got invalid sideband_info value: {sideband_info}')

        return self.main_order[instrument]
```

Could you please add some breakout strategy as an example?
For example, 10:15 to 11:15 AM breakout. I am desperately looking for that kind of example.

**Comment by guanidene** [comment]
Hi Rahul, thanks for suggesting improvements to the package.

1. Were you able to test these changes by running them? The currently available code is tested. People use these strategies out-of-the-box by doing a `pip install pyalgostrategypool; from <strategy_file> import <strategyclass>`, so its best that we test these changes first.

2. Also, may I know why would we like to change the place order method? Isn't `BuyOrderBracket` more convenient than `place_order` as you have to give fewer parameters, which means lesser chance of running into issues when designing strategies?

Look forward to your views.

**Comment by guanidene** [comment]
> Could you please add some breakout strategy as an example?
> For example, 10:15 to 11:15 AM breakout. I am desperately looking for that kind of example.

Well, we are already working on adding more strategies to the package. You can checkout the list here: https://bit.ly/2H9JaOl. Number 10 strategy is a breakout strategy. Let us know if you are interested in developing these strategies. Our market research and tech support teams can guide you in developing such strategies. See the full list of contribution guidelines [here](https://github.com/algobulls/pyalgostrategypool#contribution-guidelines) and the rewards for the same [here](https://github.com/algobulls/pyalgostrategypool/blob/master/README.md#contribution-guidelines).

**Comment by rahulmr** [comment]
> Hi Rahul, thanks for suggesting improvements to the package.
> 
> 1. Were you able to test these changes by running them? The currently available code is tested. People use these strategies out-of-the-box by doing a `pip install pyalgostrategypool; from <strategy_file> import <strategyclass>`, so its best that we test these changes first.
> 2. Also, may I know why would we like to change the place order method? Isn't `BuyOrderBracket` more convenient than `place_order` as you have to give fewer parameters, which means lesser chance of running into issues when designing strategies?
> 
> Look forward to your views.

Ohh, yes I agree BuyOrderBracket order could be a better way but since it was giving me error so I had to change to get it done. may be the core package is old at my end. May be I am missing something.
One point if you create something like BuyOrderBracket then you will have to create more methods.

`place_bo(type.sell or type.buy, .. extra parameters..)` 
`place_co(type.sell or type.buy, .. extra parameters..)` 
`place_regular(type.sell or type.buy, .. extra parameters..)` 
could be better. Though it still look too much. But even in my python scripts for zerodha I do the same I write a wrapper for place_order like buy_bo, sell_bo with very few paramters like exchange and symbol and sometimes quantity.
Some people don't use IDE, they use text editors they will find it more comfortable. 

I don't have too much experience in python and I am not so aware about the code guidelines.

**Comment by pushpakdagade** [comment]
Closing this issue.
