### ISSUE TITLE
Parameter 'TIMEPERIOD1' not found. Strategy execution cannot proceed further

### ISSUE THREAD

**Issue by shafi1908** [algobulls/pyalgostrategypool#4]
Please see https://github.com/PacktPublishing/Python-Algorithmic-Trading-Cookbook/issues/2 for detail

**Comment by pushpakdagade** [comment]
I am closing this, as this is not a real issue.

Also, a resolution has been provided to the user [here](https://github.com/PacktPublishing/Python-Algorithmic-Trading-Cookbook/issues/2) & the user has accepted it.
